# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ring/Downloads/SoFixer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ring/Downloads/SoFixer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ring/Downloads/SoFixer/CMakeFiles /Users/ring/Downloads/SoFixer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ring/Downloads/SoFixer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SoFixer

# Build rule for target.
SoFixer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SoFixer
.PHONY : SoFixer

# fast build rule for target.
SoFixer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/build
.PHONY : SoFixer/fast

ElfReader.o: ElfReader.cpp.o

.PHONY : ElfReader.o

# target to build an object file
ElfReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfReader.cpp.o
.PHONY : ElfReader.cpp.o

ElfReader.i: ElfReader.cpp.i

.PHONY : ElfReader.i

# target to preprocess a source file
ElfReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfReader.cpp.i
.PHONY : ElfReader.cpp.i

ElfReader.s: ElfReader.cpp.s

.PHONY : ElfReader.s

# target to generate assembly for a file
ElfReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfReader.cpp.s
.PHONY : ElfReader.cpp.s

ElfReader64.o: ElfReader64.cpp.o

.PHONY : ElfReader64.o

# target to build an object file
ElfReader64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfReader64.cpp.o
.PHONY : ElfReader64.cpp.o

ElfReader64.i: ElfReader64.cpp.i

.PHONY : ElfReader64.i

# target to preprocess a source file
ElfReader64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfReader64.cpp.i
.PHONY : ElfReader64.cpp.i

ElfReader64.s: ElfReader64.cpp.s

.PHONY : ElfReader64.s

# target to generate assembly for a file
ElfReader64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfReader64.cpp.s
.PHONY : ElfReader64.cpp.s

ElfRebuilder.o: ElfRebuilder.cpp.o

.PHONY : ElfRebuilder.o

# target to build an object file
ElfRebuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfRebuilder.cpp.o
.PHONY : ElfRebuilder.cpp.o

ElfRebuilder.i: ElfRebuilder.cpp.i

.PHONY : ElfRebuilder.i

# target to preprocess a source file
ElfRebuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfRebuilder.cpp.i
.PHONY : ElfRebuilder.cpp.i

ElfRebuilder.s: ElfRebuilder.cpp.s

.PHONY : ElfRebuilder.s

# target to generate assembly for a file
ElfRebuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfRebuilder.cpp.s
.PHONY : ElfRebuilder.cpp.s

ElfRebuilder64.o: ElfRebuilder64.cpp.o

.PHONY : ElfRebuilder64.o

# target to build an object file
ElfRebuilder64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfRebuilder64.cpp.o
.PHONY : ElfRebuilder64.cpp.o

ElfRebuilder64.i: ElfRebuilder64.cpp.i

.PHONY : ElfRebuilder64.i

# target to preprocess a source file
ElfRebuilder64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfRebuilder64.cpp.i
.PHONY : ElfRebuilder64.cpp.i

ElfRebuilder64.s: ElfRebuilder64.cpp.s

.PHONY : ElfRebuilder64.s

# target to generate assembly for a file
ElfRebuilder64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/ElfRebuilder64.cpp.s
.PHONY : ElfRebuilder64.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoFixer.dir/build.make CMakeFiles/SoFixer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SoFixer"
	@echo "... ElfReader.o"
	@echo "... ElfReader.i"
	@echo "... ElfReader.s"
	@echo "... ElfReader64.o"
	@echo "... ElfReader64.i"
	@echo "... ElfReader64.s"
	@echo "... ElfRebuilder.o"
	@echo "... ElfRebuilder.i"
	@echo "... ElfRebuilder.s"
	@echo "... ElfRebuilder64.o"
	@echo "... ElfRebuilder64.i"
	@echo "... ElfRebuilder64.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

